#! /bin/bash -e

ROOT_DIR="$(git rev-parse --show-toplevel)"
source "${ROOT_DIR}/scripts/helpers"

if [ -n "$(check_if_installed docker)" ]; then
    docker run -v "${PWD}:/code" sergioteula/pytools isort -c .
elif [ -n "$(check_if_installed isort)" ]; then
    isort -c .
else
    echo "Please install Docker or isort"
    exit 1
fi
