#! /bin/bash

ROOT_DIR="$(git rev-parse --show-toplevel)"
source "${ROOT_DIR}/scripts/helpers"

header "Checking code errors with flake8"

if [ -n "$(check_if_installed docker)" ]; then
    docker run -v "${PWD}:/code" sergioteula/pytools flake8 --color always .
elif [ -n "$(check_if_installed flake8)" ]; then
    flake8 --color always .
else
    error "flake8 is not installed"
    exit 1
fi

EXIT_CODE="$?"
if [ "$EXIT_CODE" = "0" ]; then
    success "Code analysis with flake8 is correct"
else
    error "There are errors detected by flake8"
    exit 1
fi
