#! /bin/bash

ROOT_DIR="$(git rev-parse --show-toplevel)"
source "${ROOT_DIR}/scripts/helpers"

header "Checking code errors with pylint"

if [ -n "$(check_if_installed docker)" ]; then
    docker run -v "${PWD}:/code" sergioteula/pytools find . -type f -name '*.py' | xargs pylint --disable=missing-docstring --disable=too-few-public-methods
elif [ -n "$(check_if_installed pylint)" ]; then
    find . -type f -name '*.py' | xargs pylint --disable=missing-docstring --disable=too-few-public-methods
else
    error "pylint is not installed"
    exit 1
fi

EXIT_CODE="$?"
if [ "$EXIT_CODE" = "0" ]; then
    success "Code analysis with pylint is correct"
else
    error "There are errors detected by pylint"
    exit 1
fi
