#! /bin/bash

ROOT_DIR="$(git rev-parse --show-toplevel)"
source "${ROOT_DIR}/scripts/helpers"

header "Checking imports order with isort"

if [ -n "$(check_if_installed docker)" ]; then
    docker run -v "${PWD}:/code" sergioteula/pytools isort -c --color .
elif [ -n "$(check_if_installed isort)" ]; then
    isort -c --color .
else
    error "isort is not installed"
    exit 1
fi

EXIT_CODE="$?"
if [ "$EXIT_CODE" = "0" ]; then
    success "Imports are correctly ordered"
else
    error "Imports order is not correct"
    exit 1
fi
