#! /bin/bash

ROOT_DIR="$(git rev-parse --show-toplevel)"
source "${ROOT_DIR}/scripts/helpers"

header "Checking code format with black"

if [ -n "$(check_if_installed docker)" ]; then
    docker run -v "${PWD}:/code" sergioteula/pytools black --check --diff --color .
elif [ -n "$(check_if_installed black)" ]; then
    black --check --diff --color .
else
    error "black is not installed"
    exit 1
fi

EXIT_CODE="$?"
if [ "$EXIT_CODE" = "0" ]; then
    success "Code is correctly formatted"
else
    error "Code should be formatted using black"
    exit 1
fi
