#! /bin/bash -e

BLUE="\033[0;34m"
GREEN="\033[0;32m"
RED="\033[0;31m"
YELLOW="\033[0;33m"
NC="\033[0m"
LINE="--------------------------------------------------------------------"

check_if_installed() {
    if [ -x "$(command -v "${1}")" ]; then
        echo "${1} is installed"
    fi
}

header(){
    echo -e "\n${BLUE}${*}\n${BLUE}${LINE}${NC}"
}

warning(){
    echo -e "${YELLOW}WARNING: ${*}${NC}"
}

error(){
    echo -e "${RED}ERROR: ${*}${NC}"
}

success(){
    echo -e "${GREEN}${*}${NC}"
}
