#! /bin/bash

ROOT_DIR="$(git rev-parse --show-toplevel)"
source "${ROOT_DIR}/scripts/helpers"

header "Running tests"

if [ -n "$(check_if_installed docker)" ]; then
    docker run -v "${PWD}:/code" sergioteula/pytools bash -c \
        "coverage run -m unittest && coverage xml && coverage html && coverage report"
elif [ -n "$(check_if_installed coverage)" ]; then
    coverage run -m unittest && coverage xml && coverage html && coverage report
else
    error "coverage is not installed"
    exit 1
fi

EXIT_CODE="$?"
if [ "$EXIT_CODE" = "0" ]; then
    success "Tests passed"
else
    error "Tests failed"
    exit 1
fi
